study:
  testStr: 哈哈


server:
  port: 8502


spring:
  profiles:
    active: dev


#xxx:
#  test:
#    username: quyixiao
#    password: 123456

XXX_TEST:
  username: quyixiao
  password: 123456
  homeLocation: 湖南省
